//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Solutions.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PuzzleInputs2015 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PuzzleInputs2015() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Solutions.Tests.PuzzleInputs2015", typeof(PuzzleInputs2015).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ()(((()))(()()()((((()(((())(()(()((((((()(()(((())))((()(((()))((())(()((()()()()(((())(((((((())))()()(()(()(())(((((()()()((())(((((()()))))()(())(((())(())((((((())())))(()())))()))))()())()())((()()((()()()()(()((((((((()()())((()()(((((()(((())((())(()))()((((()((((((((())()((()())(())((()))())((((()())(((((((((((()()(((((()(()))())(((()(()))())((()(()())())())(()(((())(())())()()(()(()((()))((()))))((((()(((()))))((((()(()(()())())()(((()((((())((((()(((()()(())()()()())((()((((((()((()()))()((()))() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2015_01_01 {
            get {
                return ResourceManager.GetString("2015_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x3x11
        ///15x27x5
        ///6x29x7
        ///30x15x9
        ///19x29x21
        ///10x4x15
        ///1x26x4
        ///1x5x18
        ///10x15x23
        ///10x14x20
        ///3x5x18
        ///29x23x30
        ///7x4x10
        ///22x24x29
        ///30x1x2
        ///19x2x5
        ///11x9x22
        ///23x15x10
        ///11x11x10
        ///30x28x5
        ///22x5x4
        ///6x26x20
        ///16x12x30
        ///10x20x5
        ///25x14x24
        ///16x17x22
        ///11x28x26
        ///1x11x10
        ///1x24x15
        ///13x17x21
        ///30x3x13
        ///20x25x17
        ///22x12x5
        ///22x20x24
        ///9x2x14
        ///6x18x8
        ///27x28x24
        ///11x17x1
        ///1x4x12
        ///5x20x13
        ///24x23x23
        ///22x1x25
        ///18x19x5
        ///5x23x13
        ///8x16x4
        ///20x21x9
        ///1x7x11
        ///8x30x17
        ///3x30x9
        ///6x16x18
        ///22x25x27
        ///9x20x26
        ///16x21x23
        ///5x24x17
        ///15x17x15
        ///26x15x10
        ///22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2015_02_01 {
            get {
                return ResourceManager.GetString("2015_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v&gt;v&lt;vvv&lt;&lt;vv^v&lt;v&gt;vv&gt;v&lt;&lt;&lt;^^^^^&lt;&lt;^&lt;vv&gt;^&gt;v^&gt;^&gt;^&gt;^&gt;^&gt;&lt;vvvv&lt;^&gt;^&lt;&lt;^&gt;&lt;&lt;&lt;^vvvv&gt;^&gt;^&gt;&lt;^v^&gt;&lt;^&lt;&gt;^^&gt;^vvv^&lt;vv&gt;&gt;^&gt;^^&lt;&gt;&gt;&lt;&gt;^&gt;vvv&gt;&gt;^vv&gt;^&lt;&gt;&lt;&gt;^&lt;v^&gt;^&gt;^&gt;&lt;vv^vv^&gt;&gt;&lt;&lt;^&gt;&lt;&lt;v&gt;&gt;&lt;&gt;^&lt;^&gt;&gt;vvv&gt;v&gt;&gt;&gt;v&lt;&lt;^&lt;&gt;&lt;^&lt;v&lt;&gt;v&gt;^^v^^^&lt;^v^^&gt;&gt;&gt;&lt;^&gt;^&gt;v&lt;&gt;^&lt;&gt;&gt;^&gt;^^v^&gt;&lt;v&lt;v&gt;&gt;&gt;&lt;&gt;v&lt;v^v&gt;^v&lt;&gt;&gt;^&gt;&lt;v&gt;^&lt;&gt;v^&gt;^&lt;&gt;^v^^^v^^&gt;&gt;vv&lt;&lt;^^&gt;&lt;^&lt;vvv&gt;^&gt;^^&lt;^&gt;&gt;^^^^^v^&lt;v&gt;vv&lt;&gt;&gt;v^v&lt;^v^^&lt;&gt;&lt;^&lt;^vv^&gt;&lt;&gt;&gt;&lt;&gt;&lt;&gt;v&gt;vvv^vv^^&lt;&lt;&gt;&lt;&lt;vvv&gt;&lt;&lt;^v^&gt;&lt;v&lt;&gt;vvv^&lt;^&gt;vvvv^&gt;^&gt;&gt;^v^&lt;v^vv&lt;^^v&lt;&gt;v&gt;vv^&lt;&gt;&gt;&lt;v&lt;&lt;&lt;^v^&lt;&lt;&gt;&lt;v&lt;^&lt;^&lt;&gt;&lt;^^^&gt;^&gt;&gt;v&gt;^&gt;v^&lt;&gt;v&gt;&lt;^&l....
        /// </summary>
        internal static string _2015_03_01 {
            get {
                return ResourceManager.GetString("2015_03_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uxcplgxnkwbdwhrp
        ///suerykeptdsutidb
        ///dmrtgdkaimrrwmej
        ///ztxhjwllrckhakut
        ///gdnzurjbbwmgayrg
        ///gjdzbtrcxwprtery
        ///fbuqqaatackrvemm
        ///pcjhsshoveaodyko
        ///lrpprussbesniilv
        ///mmsebhtqqjiqrusd
        ///vumllmrrdjgktmnb
        ///ptsqjcfbmgwdywgi
        ///mmppavyjgcfebgpl
        ///zexyxksqrqyonhui
        ///npulalteaztqqnrl
        ///mscqpccetkktaknl
        ///ydssjjlfejdxrztr
        ///jdygsbqimbxljuue
        ///ortsthjkmlonvgci
        ///jfjhsbxeorhgmstc
        ///vdrqdpojfuubjbbg
        ///xxxddetvrlpzsfpq
        ///zpjxvrmaorjpwegy
        ///laxrlkntrukjcswz
        ///pbqoungonelthcke
        ///niexeyzvrtrlgfzw
        ///zuetendekblknqng
        ///lyazavyoweyuvfye
        ///tegbldtk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2015_05_01 {
            get {
                return ResourceManager.GetString("2015_05_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn on 887,9 through 959,629
        ///turn on 454,398 through 844,448
        ///turn off 539,243 through 559,965
        ///turn off 370,819 through 676,868
        ///turn off 145,40 through 370,997
        ///turn off 301,3 through 808,453
        ///turn on 351,678 through 951,908
        ///toggle 720,196 through 897,994
        ///toggle 831,394 through 904,860
        ///toggle 753,664 through 970,926
        ///turn off 150,300 through 213,740
        ///turn on 141,242 through 932,871
        ///toggle 294,259 through 474,326
        ///toggle 678,333 through 752,957
        ///toggle 393,804 through 510,976
        ///turn off 6,964 through  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2015_06_01 {
            get {
                return ResourceManager.GetString("2015_06_01", resourceCulture);
            }
        }
    }
}
