//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Solutions.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PuzzleInputs2020 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PuzzleInputs2020() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Solutions.Tests.PuzzleInputs2020", typeof(PuzzleInputs2020).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1384
        ///1396
        ///1072
        ///1903
        ///1387
        ///1763
        ///1600
        ///1862
        ///1992
        ///1585
        ///1909
        ///1352
        ///1288
        ///1910
        ///1070
        ///1421
        ///1802
        ///1669
        ///1059
        ///1235
        ///1854
        ///1722
        ///1275
        ///198
        ///1476
        ///1588
        ///1708
        ///1217
        ///1596
        ///1355
        ///1566
        ///1973
        ///1335
        ///1480
        ///1115
        ///1272
        ///1998
        ///1821
        ///2007
        ///1721
        ///1885
        ///1420
        ///1412
        ///1487
        ///1941
        ///1835
        ///1558
        ///1061
        ///1582
        ///1940
        ///1942
        ///1210
        ///1350
        ///1175
        ///1047
        ///1456
        ///1548
        ///1110
        ///1510
        ///1995
        ///1644
        ///1968
        ///1297
        ///1198
        ///1471
        ///1360
        ///1363
        ///1528
        ///1393
        ///1365
        ///1837
        ///1886
        ///2001
        ///1161
        ///1349
        ///1787
        ///988
        ///1331
        ///1960
        ///1607
        ///1324
        ///97
        ///1986
        ///1955
        ///1773
        ///1443
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_01_01 {
            get {
                return ResourceManager.GetString("2020_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1721
        ///979
        ///366
        ///299
        ///675
        ///1456.
        /// </summary>
        internal static string _2020_01_01_example {
            get {
                return ResourceManager.GetString("2020_01_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-4 j: jjjqzmgbjwpj
        ///2-4 w: sckwwf
        ///1-13 b: bcbbbbbbbbbbhbb
        ///10-11 x: xjxxxxxxxxzxxx
        ///13-14 d: dddddddddddddd
        ///16-18 s: ksttbjsstpnsvtcjnx
        ///3-8 k: gkkqkbpvkrx
        ///3-7 c: mccnjgcxkfkp
        ///3-7 b: hgbqzrjvwqbfc
        ///8-14 r: rrrrrrrfrrrtrrrr
        ///5-6 v: vvvvwpvvv
        ///4-5 b: zfkpb
        ///12-13 n: nwnwdplnhfhlnnnntfn
        ///9-14 z: sxzjzfrzztczlw
        ///1-14 n: vnnnnnnnnnnnnnnnnnnn
        ///4-6 b: bbbsbb
        ///2-7 x: xxsjxpxx
        ///6-8 z: wzfqzzzzn
        ///2-17 b: cbbmwqmjxhkvjnfbx
        ///3-9 h: hhhhhghhshh
        ///3-13 m: mmzmmmmmmmmmxmmmb
        ///2-4 v: xnxv
        ///3-4 s: tsxsns
        ///1-11 m: mmmmzvm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_02_01 {
            get {
                return ResourceManager.GetString("2020_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 a: abcde
        ///1-3 b: cdefg
        ///2-9 c: ccccccccc.
        /// </summary>
        internal static string _2020_02_01_example {
            get {
                return ResourceManager.GetString("2020_02_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....#...#####..##.#..##..#....#
        ///..##.#.#.........#.#......##...
        ///#.#.#.##.##...#.......#...#..#.
        ///..##.............#.#.##.....#..
        ///##......#.............#....#...
        ///.....##..#.....##.#.......##..#
        ///.##.....#........##...##.#....#
        ///.##......#.#......#.....#..##.#
        ///##....#..#...#...#...##.#...##.
        ///##........##.#...##......#.#.#.
        ///..#.#........#...##.....#.....#
        ///..#.......####.#....#..#####...
        ///.##..#..#..##.#.....###.#..#...
        ///......###..##.....#.#.#..###.#.
        ///..#.#...#..##.....#....#.#.....
        ///.....#.#...#.###. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_03_01 {
            get {
                return ResourceManager.GetString("2020_03_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..##.......
        ///#...#...#..
        ///.#....#..#.
        ///..#.#...#.#
        ///.#...##..#.
        ///..#.##.....
        ///.#.#.#....#
        ///.#........#
        ///#.##...#...
        ///#...##....#
        ///.#..#...#.#.
        /// </summary>
        internal static string _2020_03_01_example {
            get {
                return ResourceManager.GetString("2020_03_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:1928 cid:150 pid:476113241 eyr:2039 hcl:a5ac0f
        ///ecl:#25f8d2
        ///byr:2027 hgt:190
        ///
        ///hgt:168cm eyr:2026 ecl:hzl hcl:#fffffd cid:169 pid:920076943
        ///byr:1929 iyr:2013
        ///
        ///hgt:156cm ecl:brn eyr:2023
        ///iyr:2011
        ///hcl:#6b5442 pid:328412891 byr:1948
        ///
        ///byr:1950 iyr:2019 eyr:2020 ecl:amb cid:279 pid:674907993 hgt:189cm hcl:#602927
        ///
        ///byr:1976
        ///ecl:hzl iyr:2015 hgt:178cm eyr:2022 hcl:#341e13
        ///pid:473630095
        ///
        ///iyr:2020 eyr:2023 ecl:blu byr:1984
        ///hgt:163cm hcl:#866857 pid:628113926
        ///
        ///ecl:amb
        ///pid:312508073
        ///hgt:70in by [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_04_01 {
            get {
                return ResourceManager.GetString("2020_04_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
        ///byr:1937 iyr:2017 cid:147 hgt:183cm
        ///
        ///iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
        ///hcl:#cfa07d byr:1929
        ///
        ///hcl:#ae17e1 iyr:2013
        ///eyr:2024
        ///ecl:brn pid:760753108 byr:1931
        ///hgt:179cm
        ///
        ///hcl:#cfa07d eyr:2025 pid:166559648
        ///iyr:2011 ecl:brn hgt:59in.
        /// </summary>
        internal static string _2020_04_01_example {
            get {
                return ResourceManager.GetString("2020_04_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:1972 cid:100
        ///hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926
        ///
        ///iyr:2019
        ///hcl:#602927 eyr:1967 hgt:170cm
        ///ecl:grn pid:012533040 byr:1946
        ///
        ///hcl:dab227 iyr:2012
        ///ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277
        ///
        ///hgt:59cm ecl:zzz
        ///eyr:2038 hcl:74454a iyr:2023
        ///pid:3556412378 byr:2007.
        /// </summary>
        internal static string _2020_04_02_invalid {
            get {
                return ResourceManager.GetString("2020_04_02_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:1972 cid:100
        ///hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid:88
        ///pid:545766238 ecl:hzl
        ///eyr:2022
        ///
        ///iyr:2019
        ///hcl:#602927 eyr:1967 hgt:170cm
        ///ecl:grn pid:012533040 byr:1946
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:dab227 iyr:2012
        ///ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277
        ///
        ///hgt:59cm ecl:zzz
        ///eyr:2038 hcl:74454a iyr:2023
        ///pid:3556412378 byr:2007
        ///
        ///pid:087499704 hgt:74in ecl:grn iyr: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_04_02_mixed {
            get {
                return ResourceManager.GetString("2020_04_02_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980
        ///hcl:#623a2f
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid:88
        ///pid:545766238 ecl:hzl
        ///eyr:2022
        ///
        ///iyr:2010 hgt:158cm hcl:#b6652a ecl:blu byr:1944 eyr:2021 pid:093154719pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980
        ///hcl:#623a2f
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_04_02_valid {
            get {
                return ResourceManager.GetString("2020_04_02_valid", resourceCulture);
            }
        }
    }
}
