//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Solutions.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PuzzleInputs2020 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PuzzleInputs2020() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Solutions.Tests.PuzzleInputs2020", typeof(PuzzleInputs2020).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1384
        ///1396
        ///1072
        ///1903
        ///1387
        ///1763
        ///1600
        ///1862
        ///1992
        ///1585
        ///1909
        ///1352
        ///1288
        ///1910
        ///1070
        ///1421
        ///1802
        ///1669
        ///1059
        ///1235
        ///1854
        ///1722
        ///1275
        ///198
        ///1476
        ///1588
        ///1708
        ///1217
        ///1596
        ///1355
        ///1566
        ///1973
        ///1335
        ///1480
        ///1115
        ///1272
        ///1998
        ///1821
        ///2007
        ///1721
        ///1885
        ///1420
        ///1412
        ///1487
        ///1941
        ///1835
        ///1558
        ///1061
        ///1582
        ///1940
        ///1942
        ///1210
        ///1350
        ///1175
        ///1047
        ///1456
        ///1548
        ///1110
        ///1510
        ///1995
        ///1644
        ///1968
        ///1297
        ///1198
        ///1471
        ///1360
        ///1363
        ///1528
        ///1393
        ///1365
        ///1837
        ///1886
        ///2001
        ///1161
        ///1349
        ///1787
        ///988
        ///1331
        ///1960
        ///1607
        ///1324
        ///97
        ///1986
        ///1955
        ///1773
        ///1443
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_01_01 {
            get {
                return ResourceManager.GetString("2020_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1721
        ///979
        ///366
        ///299
        ///675
        ///1456.
        /// </summary>
        internal static string _2020_01_01_example {
            get {
                return ResourceManager.GetString("2020_01_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-4 j: jjjqzmgbjwpj
        ///2-4 w: sckwwf
        ///1-13 b: bcbbbbbbbbbbhbb
        ///10-11 x: xjxxxxxxxxzxxx
        ///13-14 d: dddddddddddddd
        ///16-18 s: ksttbjsstpnsvtcjnx
        ///3-8 k: gkkqkbpvkrx
        ///3-7 c: mccnjgcxkfkp
        ///3-7 b: hgbqzrjvwqbfc
        ///8-14 r: rrrrrrrfrrrtrrrr
        ///5-6 v: vvvvwpvvv
        ///4-5 b: zfkpb
        ///12-13 n: nwnwdplnhfhlnnnntfn
        ///9-14 z: sxzjzfrzztczlw
        ///1-14 n: vnnnnnnnnnnnnnnnnnnn
        ///4-6 b: bbbsbb
        ///2-7 x: xxsjxpxx
        ///6-8 z: wzfqzzzzn
        ///2-17 b: cbbmwqmjxhkvjnfbx
        ///3-9 h: hhhhhghhshh
        ///3-13 m: mmzmmmmmmmmmxmmmb
        ///2-4 v: xnxv
        ///3-4 s: tsxsns
        ///1-11 m: mmmmzvm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_02_01 {
            get {
                return ResourceManager.GetString("2020_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 a: abcde
        ///1-3 b: cdefg
        ///2-9 c: ccccccccc.
        /// </summary>
        internal static string _2020_02_01_example {
            get {
                return ResourceManager.GetString("2020_02_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....#...#####..##.#..##..#....#
        ///..##.#.#.........#.#......##...
        ///#.#.#.##.##...#.......#...#..#.
        ///..##.............#.#.##.....#..
        ///##......#.............#....#...
        ///.....##..#.....##.#.......##..#
        ///.##.....#........##...##.#....#
        ///.##......#.#......#.....#..##.#
        ///##....#..#...#...#...##.#...##.
        ///##........##.#...##......#.#.#.
        ///..#.#........#...##.....#.....#
        ///..#.......####.#....#..#####...
        ///.##..#..#..##.#.....###.#..#...
        ///......###..##.....#.#.#..###.#.
        ///..#.#...#..##.....#....#.#.....
        ///.....#.#...#.###. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_03_01 {
            get {
                return ResourceManager.GetString("2020_03_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..##.......
        ///#...#...#..
        ///.#....#..#.
        ///..#.#...#.#
        ///.#...##..#.
        ///..#.##.....
        ///.#.#.#....#
        ///.#........#
        ///#.##...#...
        ///#...##....#
        ///.#..#...#.#.
        /// </summary>
        internal static string _2020_03_01_example {
            get {
                return ResourceManager.GetString("2020_03_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iyr:1928 cid:150 pid:476113241 eyr:2039 hcl:a5ac0f
        ///ecl:#25f8d2
        ///byr:2027 hgt:190
        ///
        ///hgt:168cm eyr:2026 ecl:hzl hcl:#fffffd cid:169 pid:920076943
        ///byr:1929 iyr:2013
        ///
        ///hgt:156cm ecl:brn eyr:2023
        ///iyr:2011
        ///hcl:#6b5442 pid:328412891 byr:1948
        ///
        ///byr:1950 iyr:2019 eyr:2020 ecl:amb cid:279 pid:674907993 hgt:189cm hcl:#602927
        ///
        ///byr:1976
        ///ecl:hzl iyr:2015 hgt:178cm eyr:2022 hcl:#341e13
        ///pid:473630095
        ///
        ///iyr:2020 eyr:2023 ecl:blu byr:1984
        ///hgt:163cm hcl:#866857 pid:628113926
        ///
        ///ecl:amb
        ///pid:312508073
        ///hgt:70in by [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_04_01 {
            get {
                return ResourceManager.GetString("2020_04_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
        ///byr:1937 iyr:2017 cid:147 hgt:183cm
        ///
        ///iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
        ///hcl:#cfa07d byr:1929
        ///
        ///hcl:#ae17e1 iyr:2013
        ///eyr:2024
        ///ecl:brn pid:760753108 byr:1931
        ///hgt:179cm
        ///
        ///hcl:#cfa07d eyr:2025 pid:166559648
        ///iyr:2011 ecl:brn hgt:59in.
        /// </summary>
        internal static string _2020_04_01_example {
            get {
                return ResourceManager.GetString("2020_04_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:1972 cid:100
        ///hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926
        ///
        ///iyr:2019
        ///hcl:#602927 eyr:1967 hgt:170cm
        ///ecl:grn pid:012533040 byr:1946
        ///
        ///hcl:dab227 iyr:2012
        ///ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277
        ///
        ///hgt:59cm ecl:zzz
        ///eyr:2038 hcl:74454a iyr:2023
        ///pid:3556412378 byr:2007.
        /// </summary>
        internal static string _2020_04_02_invalid {
            get {
                return ResourceManager.GetString("2020_04_02_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:1972 cid:100
        ///hcl:#18171d ecl:amb hgt:170 pid:186cm iyr:2018 byr:1926
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid:88
        ///pid:545766238 ecl:hzl
        ///eyr:2022
        ///
        ///iyr:2019
        ///hcl:#602927 eyr:1967 hgt:170cm
        ///ecl:grn pid:012533040 byr:1946
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:dab227 iyr:2012
        ///ecl:brn hgt:182cm pid:021572410 eyr:2020 byr:1992 cid:277
        ///
        ///hgt:59cm ecl:zzz
        ///eyr:2038 hcl:74454a iyr:2023
        ///pid:3556412378 byr:2007
        ///
        ///pid:087499704 hgt:74in ecl:grn iyr: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_04_02_mixed {
            get {
                return ResourceManager.GetString("2020_04_02_mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980
        ///hcl:#623a2f
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid:88
        ///pid:545766238 ecl:hzl
        ///eyr:2022
        ///
        ///iyr:2010 hgt:158cm hcl:#b6652a ecl:blu byr:1944 eyr:2021 pid:093154719.
        /// </summary>
        internal static string _2020_04_02_valid {
            get {
                return ResourceManager.GetString("2020_04_02_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFBBFFBRRR
        ///FBFBBBBLRR
        ///BFBBBBBLRR
        ///FBBFFFBLLR
        ///FFBBFBBLLR
        ///FBFFFBBLRL
        ///FBFFFFBRRL
        ///FBBBBBFLLR
        ///BFFFBBFLRR
        ///FFBBFBFRLL
        ///BFFFBFBLRL
        ///BFBBBFBLLL
        ///FFFBFBBLLR
        ///FFBBBFBRLR
        ///FFFBBBBLRR
        ///BFFFFBFRRL
        ///FBFFBBBRLR
        ///BFFFFBFRLR
        ///BFBFBFBRLR
        ///FFBFBFFLLR
        ///BBFBBFFRLL
        ///BFFBBFFRRR
        ///BBFBBFFRLR
        ///FFBBBBFLRR
        ///FFFFBBBLLR
        ///FBBBBBBRRR
        ///FBFFFBBRLL
        ///FFBFBFFLLL
        ///FFFBBFFRRL
        ///BBFFBBFLRL
        ///BFFFBBBLRR
        ///FFBFFBFLLR
        ///FFBFBFBRRR
        ///FBBFBBFRLL
        ///FFFBBFFLLR
        ///FBFFBFBLLR
        ///FBFFBBFLRL
        ///BBFFFFFLRL
        ///FBBBFFFLRR
        ///BBFFBBBLRR
        ///BFFFFFFRLL
        ///BFFBFFFLRL
        ///FFBFBBBL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_05_01 {
            get {
                return ResourceManager.GetString("2020_05_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBFBBFFRLR
        ///BFFFBBFRRR
        ///FFFBBBFRRR
        ///BBFFBBFRLL.
        /// </summary>
        internal static string _2020_05_01_example {
            get {
                return ResourceManager.GetString("2020_05_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xtpmjeuayzkflcdo
        ///zdaeyxlpftkmojc
        ///
        ///ifnkhzalvprjtyus
        ///lmihuzrytjns
        ///uilmsotygbnhrzj
        ///uwslqctjnirzxhy
        ///
        ///lhuydwqxaempbisrnfcjtvz
        ///rvtcegbhljadfpxzsiuyqwnm
        ///rzyvtefjdsplucmqbinahxw
        ///
        ///whlxgytuoaidpfrsbvmkjqez
        ///iwfghlytovbpdemzanjq
        ///mpejclwhqziatybogvdf
        ///
        ///qsmuehbvfiwlkx
        ///gtmdsbrqfwhk
        ///
        ///lagwjpd
        ///dpglwja
        ///qgdawplj
        ///
        ///faqjpheg
        ///acnfgtkzj
        ///msjdfox
        ///
        ///gsqhdrcvyxbp
        ///yhvgpsqxcbdr
        ///drqvgxhyspcb
        ///cgqrypdhbxvs
        ///hbdxgyscjqprv
        ///
        ///bgahiyplewc
        ///qaprike
        ///aojpszixe
        ///airpksoe
        ///mpzaiek
        ///
        ///ihyudtfbjqnxop
        ///poyiuqjdlhmtxb
        ///
        ///gw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_06_01 {
            get {
                return ResourceManager.GetString("2020_06_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc
        ///
        ///a
        ///b
        ///c
        ///
        ///ab
        ///ac
        ///
        ///a
        ///a
        ///a
        ///a
        ///
        ///b.
        /// </summary>
        internal static string _2020_06_01_example {
            get {
                return ResourceManager.GetString("2020_06_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shiny aqua bags contain 1 dark white bag.
        ///muted blue bags contain 1 vibrant lavender bag, 4 dotted silver bags, 2 dim indigo bags.
        ///drab gray bags contain 5 mirrored white bags, 1 light green bag, 5 shiny lavender bags, 5 faded aqua bags.
        ///muted indigo bags contain 4 muted chartreuse bags, 2 dotted teal bags.
        ///drab white bags contain 2 dull fuchsia bags, 1 vibrant bronze bag.
        ///dim lavender bags contain 4 muted tan bags.
        ///dotted tomato bags contain 1 mirrored lime bag, 2 vibrant white bags.
        ///clear orange ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_07_01 {
            get {
                return ResourceManager.GetString("2020_07_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light red bags contain 1 bright white bag, 2 muted yellow bags.
        ///dark orange bags contain 3 bright white bags, 4 muted yellow bags.
        ///bright white bags contain 1 shiny gold bag.
        ///muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
        ///shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
        ///dark olive bags contain 3 faded blue bags, 4 dotted black bags.
        ///vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
        ///faded blue bags contain no other bags.
        ///dotted black bags contain no othe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_07_01_example {
            get {
                return ResourceManager.GetString("2020_07_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shiny gold bags contain 2 dark red bags.
        ///dark red bags contain 2 dark orange bags.
        ///dark orange bags contain 2 dark yellow bags.
        ///dark yellow bags contain 2 dark green bags.
        ///dark green bags contain 2 dark blue bags.
        ///dark blue bags contain 2 dark violet bags.
        ///dark violet bags contain no other bags..
        /// </summary>
        internal static string _2020_07_02_example {
            get {
                return ResourceManager.GetString("2020_07_02_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +22
        ///acc +34
        ///jmp +167
        ///acc +46
        ///acc +25
        ///acc -10
        ///acc +11
        ///jmp +540
        ///acc +0
        ///jmp +242
        ///acc +26
        ///acc +46
        ///jmp +242
        ///jmp +287
        ///acc -8
        ///acc +30
        ///acc +3
        ///nop +350
        ///jmp +471
        ///acc +2
        ///acc +0
        ///acc +14
        ///jmp +207
        ///jmp +1
        ///acc -10
        ///acc +12
        ///jmp +281
        ///acc +18
        ///jmp +515
        ///acc -18
        ///acc +33
        ///jmp +379
        ///acc +48
        ///acc +38
        ///jmp +220
        ///acc +44
        ///nop +546
        ///acc +21
        ///jmp +537
        ///acc +33
        ///nop +224
        ///nop +379
        ///jmp +2
        ///jmp -30
        ///jmp +246
        ///acc -14
        ///acc -3
        ///jmp +410
        ///acc +50
        ///nop +323
        ///acc +2
        ///acc +24
        ///jmp +25
        ///jmp +372
        ///acc +29
        ///acc +1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_08_01 {
            get {
                return ResourceManager.GetString("2020_08_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nop +0
        ///acc +1
        ///jmp +4
        ///acc +3
        ///jmp -3
        ///acc -99
        ///acc +1
        ///jmp -4
        ///acc +6.
        /// </summary>
        internal static string _2020_08_01_example {
            get {
                return ResourceManager.GetString("2020_08_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///24
        ///36
        ///21
        ///45
        ///47
        ///20
        ///46
        ///31
        ///30
        ///22
        ///27
        ///34
        ///29
        ///17
        ///8
        ///13
        ///33
        ///35
        ///18
        ///26
        ///44
        ///5
        ///41
        ///42
        ///7
        ///28
        ///12
        ///43
        ///61
        ///68
        ///36
        ///70
        ///46
        ///15
        ///19
        ///20
        ///30
        ///21
        ///51
        ///17
        ///24
        ///31
        ///37
        ///58
        ///22
        ///25
        ///26
        ///49
        ///27
        ///32
        ///45
        ///29
        ///34
        ///50
        ///35
        ///38
        ///52
        ///36
        ///39
        ///40
        ///41
        ///67
        ///60
        ///77
        ///42
        ///72
        ///51
        ///47
        ///48
        ///55
        ///53
        ///56
        ///70
        ///61
        ///85
        ///81
        ///63
        ///90
        ///71
        ///73
        ///75
        ///104
        ///76
        ///79
        ///88
        ///83
        ///106
        ///89
        ///93
        ///95
        ///167
        ///103
        ///100
        ///101
        ///128
        ///134
        ///165
        ///124
        ///166
        ///136
        ///138
        ///139
        ///200
        ///154
        ///148
        ///176
        ///155
        ///159
        ///189
        ///171
        ///188
        ///196
        ///240
        ///194
        ///195
        ///201
        ///248
        ///235
        ///360
        ///334
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_09_01 {
            get {
                return ResourceManager.GetString("2020_09_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///20
        ///15
        ///25
        ///47
        ///40
        ///62
        ///55
        ///65
        ///95
        ///102
        ///117
        ///150
        ///182
        ///127
        ///219
        ///299
        ///277
        ///309
        ///576.
        /// </summary>
        internal static string _2020_09_01_example {
            get {
                return ResourceManager.GetString("2020_09_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84
        ///60
        ///10
        ///23
        ///126
        ///2
        ///128
        ///63
        ///59
        ///69
        ///127
        ///73
        ///140
        ///55
        ///154
        ///133
        ///36
        ///139
        ///4
        ///70
        ///110
        ///97
        ///153
        ///105
        ///41
        ///106
        ///79
        ///145
        ///35
        ///134
        ///146
        ///148
        ///13
        ///77
        ///49
        ///107
        ///46
        ///138
        ///88
        ///152
        ///83
        ///120
        ///52
        ///114
        ///159
        ///158
        ///53
        ///76
        ///16
        ///28
        ///89
        ///25
        ///42
        ///66
        ///119
        ///3
        ///17
        ///67
        ///94
        ///99
        ///7
        ///56
        ///85
        ///122
        ///18
        ///20
        ///43
        ///160
        ///54
        ///113
        ///29
        ///130
        ///19
        ///135
        ///30
        ///80
        ///116
        ///91
        ///161
        ///115
        ///141
        ///102
        ///37
        ///157
        ///129
        ///34
        ///147
        ///142
        ///151
        ///68
        ///78
        ///24
        ///90
        ///121
        ///123
        ///33
        ///98
        ///1
        ///40.
        /// </summary>
        internal static string _2020_10_01 {
            get {
                return ResourceManager.GetString("2020_10_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///10
        ///15
        ///5
        ///1
        ///11
        ///7
        ///19
        ///6
        ///12
        ///4.
        /// </summary>
        internal static string _2020_10_01_example1 {
            get {
                return ResourceManager.GetString("2020_10_01_example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28
        ///33
        ///18
        ///42
        ///31
        ///14
        ///46
        ///20
        ///48
        ///47
        ///24
        ///23
        ///49
        ///45
        ///19
        ///38
        ///39
        ///11
        ///1
        ///32
        ///25
        ///35
        ///8
        ///17
        ///7
        ///9
        ///4
        ///2
        ///34
        ///10
        ///3.
        /// </summary>
        internal static string _2020_10_01_example2 {
            get {
                return ResourceManager.GetString("2020_10_01_example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLL.LLLLLLLLLLLLLLLL.LLLLLLLL.LLLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLL.LL.L.LLLL.LLLLLLLLL.LLLLL
        ///LLLLLLLL.LLL.LLLL.LLLLL.LLLLLLLL.LLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLL.LLLL.LLLLLLLLL.LLLLLLLLLL
        ///LLLLLLLLLLLLLLLLL.LLLLL.L.LLLLLL..LLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLL.LLLLLLLLL.LLLL.LLLL.LLLLL
        ///LLL.LL.LLLLLLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLLLLLLLLLLLLLL.LLLLLLL.LLLL.LLLLLLLLL.LLLLLL..LL
        ///LLLLLLLLLLLL.LLLL.LLLLLLLLLLLLLL.LLLLLLLLLLLLLLLLLLLLLLLLL.LLLL.LL.LLLLLLLLL.LLLLLLLLL..LLLL
        ///LLLLLLLLLLL..LLLL.LLLLL.LLLLLLLL.LLLLLLLLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_11_01 {
            get {
                return ResourceManager.GetString("2020_11_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.LL.LL.LL
        ///LLLLLLL.LL
        ///L.L.L..L..
        ///LLLL.LL.LL
        ///L.LL.LL.LL
        ///L.LLLLL.LL
        ///..L.L.....
        ///LLLLLLLLLL
        ///L.LLLLLL.L
        ///L.LLLLL.LL.
        /// </summary>
        internal static string _2020_11_01_example {
            get {
                return ResourceManager.GetString("2020_11_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3
        ///R180
        ///S1
        ///F2
        ///R90
        ///W3
        ///F81
        ///L270
        ///W5
        ///F30
        ///R90
        ///E5
        ///S3
        ///F44
        ///R180
        ///S4
        ///F21
        ///R270
        ///F2
        ///W3
        ///F36
        ///L90
        ///S1
        ///E3
        ///F86
        ///S2
        ///F98
        ///E4
        ///F93
        ///W5
        ///R90
        ///W5
        ///F4
        ///E4
        ///F6
        ///R90
        ///N2
        ///L90
        ///F52
        ///R90
        ///W4
        ///F30
        ///E5
        ///W5
        ///N4
        ///F1
        ///N3
        ///W2
        ///F89
        ///E1
        ///L90
        ///W1
        ///R90
        ///F67
        ///N5
        ///R90
        ///F95
        ///L90
        ///E4
        ///S4
        ///E2
        ///N4
        ///E4
        ///R90
        ///R90
        ///F99
        ///W1
        ///R90
        ///E4
        ///F26
        ///W5
        ///L90
        ///F89
        ///E2
        ///F18
        ///W3
        ///L90
        ///F64
        ///N2
        ///F69
        ///L90
        ///F81
        ///R90
        ///E4
        ///L90
        ///N5
        ///E2
        ///F25
        ///W4
        ///L180
        ///N2
        ///R90
        ///F82
        ///R90
        ///S3
        ///F64
        ///E4
        ///F11
        ///R90
        ///F93
        ///E2
        ///F18
        ///L90
        ///R180
        ///F13
        ///L90
        ///F37
        ///L90
        ///F63
        ///R90
        ///W3
        ///N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_12_01 {
            get {
                return ResourceManager.GetString("2020_12_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10
        ///N3
        ///F7
        ///R90
        ///F11.
        /// </summary>
        internal static string _2020_12_01_example {
            get {
                return ResourceManager.GetString("2020_12_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000511
        ///29,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,37,x,x,x,x,x,409,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,17,13,19,x,x,x,23,x,x,x,x,x,x,x,353,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,41.
        /// </summary>
        internal static string _2020_13_01 {
            get {
                return ResourceManager.GetString("2020_13_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 939
        ///7,13,x,x,59,x,31,19.
        /// </summary>
        internal static string _2020_13_01_example {
            get {
                return ResourceManager.GetString("2020_13_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = X10X11X1000101X1XX001100001X101X0111
        ///mem[27041] = 56559
        ///mem[43069] = 56082467
        ///mem[55125] = 25536
        ///mem[13313] = 3968
        ///mask = 0X01110110X10101X01100110000X0X010X0
        ///mem[51810] = 586700041
        ///mem[5546] = 73582083
        ///mem[64563] = 1709385
        ///mask = X10X1X01000X1XXX1011010X0101001X1100
        ///mem[55081] = 164951
        ///mem[57902] = 941479
        ///mem[64412] = 168227
        ///mem[38991] = 7285
        ///mem[32442] = 4026389
        ///mem[13462] = 11389
        ///mask = 100XX0010X000001X1X1000110011X000011
        ///mem[30898] = 16273
        ///mem[58759] = 129155
        ///mem[32283] = 1627 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2020_14_01 {
            get {
                return ResourceManager.GetString("2020_14_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = XXXXXXXXXXXXXXXXXXXXXXXXXXXXX1XXXX0X
        ///mem[8] = 11
        ///mem[7] = 101
        ///mem[8] = 0.
        /// </summary>
        internal static string _2020_14_01_example {
            get {
                return ResourceManager.GetString("2020_14_01_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mask = 000000000000000000000000000000X1001X
        ///mem[42] = 100
        ///mask = 00000000000000000000000000000000X0XX
        ///mem[26] = 1.
        /// </summary>
        internal static string _2020_14_02_example {
            get {
                return ResourceManager.GetString("2020_14_02_example", resourceCulture);
            }
        }
    }
}
